### ISSUE TITLE
Support Request: ESP-ME3 with no remaining time under ioBroker

### ISSUE THREAD

**Issue by UlfHRO** [donavanbecker/rainbird#10]
### Describe Your Problem

I am using the RainBird integration for ioBroker (ioBroker.rainbird) with my ESP-ME3. I understand that the ioBroker integration is based on this library. All function work fine, except the indication of the remaining time during activation by the programs. I assume this is related to the ESP-ME3 type. Could we try to troubleshoot this...!? Thanks... 

### Device & Model

ESP-ME3

### Node.js Version

n.a.

### Rainbird Version

n.a.

### Operating System

ioBroker raspberry pi

**Comment by donavanbecker** [comment]
Should already be supported:

https://github.com/donavanbecker/homebridge-rainbird/issues/396
